### ISSUE TITLE
Attribute error in Django 2.0

### ISSUE THREAD

**Issue by dizballanze** [CleanCut/green#177] opened 2018-01-17 08:20 UTC
Hi, seems that green doesn't work with Django 2.0.
```
# python manage.py test

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/core/management/commands/test.py", line 59, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/vagrant/venv/lib/python3.6/site-packages/green/djangorunner.py", line 124, in run_tests
    result = run(suite, stream, args)
  File "/home/vagrant/venv/lib/python3.6/site-packages/green/runner.py", line 115, in run
    result.addProtoTestResult(proto_test_result)
  File "/home/vagrant/venv/lib/python3.6/site-packages/green/result.py", line 346, in addProtoTestResult
    for test, err in proto_test_result.errors:
AttributeError: 'NoneType' object has no attribute 'errors'
```

**Comment by CleanCut** [comment] 2018-01-19 21:44
@dizballanze I have not been able to reproduce this error.  I have been experimenting with:
- django 2.0.1
- green 2.12.0
- coverage 4.4.2
- python 3.6.4
- on macOS 10.13.2

Can you provide some way to reproduce the error?  If you are working on an open source project, I could try that directly.  If not, it would be great if you could produce a small django project which simply reproduces the error.

If you could also provide me with your OS and component versions, that may help.

**Comment by CleanCut** [comment] 2018-01-19 21:46
Also, what does your config file look like, and where is it located relative to your project?

**Comment by dizballanze** [comment] 2018-01-20 10:04
I use packages and Python version as you described above.

Sometimes it raises described above error. In other tries, it raises a bunch of database errors for some of the tests while other tests pass. Some of the errors it raises:


```
  File "/home/vagrant/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
psycopg2.DatabaseError: SSL error: decryption failed or bad record mac
```

I managed to fix this by settings `ssl = false` in `postgresql.conf`. But why this works with default test runner?

```
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

Many of `psycopg2.IntegrityError`

**Comment by Ogaday** [comment] 2018-01-22 16:41
Just a hunch, as I don't know anything about Django, but this has the hallmarks of concurrency errors.

I had similar issues in another project, wherein green would through different errors on different runs, and using `python -m unittest` instead didn't raise any errors at all. I figured out that it was because I hadn't considered the fact that green uses multiprocessing, and I was accessing the same the resources in different test modules. Could it be the same situation here?

**Comment by CleanCut** [comment] 2018-01-23 19:23
It could be the same situation.  For systems not designed for concurrent testing (django), I recommend specifying in your green configuration file to use only one process.

`processes = 1`

Please let me know if that helps.  If it does, then I will add that advice to the [Django section of the readme](https://github.com/CleanCut/green#django).

**Comment by CleanCut** [comment] 2018-01-23 19:47
Hmm...if the multiprocessing ended up being the problem, it may be worth adding a feature to Green to auto-detect when it is running under Django and defaulting to 1 process in that case.

**Comment by dizballanze** [comment] 2018-01-24 08:41
It works with `processes = 1`.
But it's possible to run tests in parallel [since version 1.9](https://docs.djangoproject.com/en/2.0/releases/1.9/#running-tests-in-parallel) with default Django test runner.

**Comment by CleanCut** [comment] 2018-01-29 17:35
Okay, I'll go ahead and close this, then.

**Closed by CleanCut** 2018-01-29 17:35 UTC
Labels: bug

**Comment by dizballanze** [comment] 2018-01-29 18:29
Maybe `green` can support parallel tests in new versions of Django? I've tried to set `--parallel` option of the Django test runner equal to `processes` from green. It works but some tests still failing with database errors.

**Comment by CleanCut** [comment] 2018-02-21 21:44
That would be cool. Does Django have any documentation about how a test runner can interact with Django to support parallel tests?

**Comment by charlsagente** [comment] 2018-06-12 13:37
@CleanCut It is possible in the django documentation. https://docs.djangoproject.com/en/2.0/topics/testing/overview/ with the **--parallel** flag. BTW Thanks I had the same issue and **processes=1** solved the issue.

**Comment by CleanCut** [comment] 2018-06-12 20:18
@charlsagente Awesome, I'm so glad it solved the problem for you!

Also, thank you for the pointer to the `--parallel` flag.  I created #190 to track making Django integration more pleasant.
