### ISSUE TITLE
Adding Xunit/Junit Xml report

### ISSUE THREAD

**Issue by JayZar21** [CleanCut/green#104] opened 2015-11-26 13:11 UTC
It is a standard feature which is needed for Jenking and CI integration.
Please consider it.
Thanks.

**Comment by CleanCut** [comment] 2016-05-26 22:42
This might be a duplicate of #34 

I hope to do some feature to enable integration with Jenkins.

**Comment by carldunham** [comment] 2016-11-18 17:38
A nice-to-have for us CircleCI users also

**Comment by CleanCut** [comment] 2016-11-18 17:42
If someone would like to give implementing that type of output a try, I would be happy to point them in the right direction and review PR's.

**Closed** 2019-04-10 17:57 UTC
Labels: enhancement, help wanted

**Comment by CleanCut** [comment] 2019-04-11 20:57
✅ `-j/--junit-report` shipped in 2.15.0, which was just released.  Thanks to @fchauvel for contributing this feature! 🎉
